plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.bhavani.barcodeprinter"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.bhavani.barcodeprinter"
        minSdk = 21          // Lowered from 26 to support this TVS POS tablet on Android 7.1.2 (API 25).
                              // USB Host API classes (UsbManager/UsbDeviceConnection/etc.) have existed
                              // since API 12, so the printer code itself works fine down here.
        targetSdk = 34
        versionCode = 2
        versionName = "2.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation(platform("androidx.compose:compose-bom:2024.09.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.6")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.6")

    // Navigation between screens (Print / Database / Settings / Designer / etc.)
    implementation("androidx.navigation:navigation-compose:2.8.0")

    // Local database: items, price history, custom fields, print history, recycle bin
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // Background job for auto-purging recycle-bin items after 30 days
    implementation("androidx.work:work-runtime-ktx:2.9.1")

    // Settings + single label template storage (small JSON blobs)
    implementation("androidx.datastore:datastore-preferences:1.1.1")

    // Barcode rendering for the on-screen preview only.
    // The actual printed barcode is generated by the printer itself from raw TSPL.
    implementation("com.google.zxing:core:3.5.3")
}
